version: '3.8'

services:
  # --- База даних (PostgreSQL) ---
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: repair_db
    ports:
      - "5432:5432"

  # --- Keycloak (Сервер авторизації) ---
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      # Підключаємо файл експорту, щоб Keycloak знав про Alice і налаштування
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8180:8080"
    depends_on:
      - postgres

  # --- Твої мікросервіси (Запускаємо як Java jar) ---
  # Увага: Для цього треба спочатку зробити 'mvn package' для кожного

  # request-service: ... (поки не пишемо, запустимо їх вручну для тесту або пізніше додамо)